version: 2

jobs:
  build:
    working_directory: ~/arrow
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run:
          name: Clean build
          command: ./gradlew clean build
