language: kotlin
sudo: required
dist: trusty

jdk:
- oraclejdk8

stages:
  #- name: build
  - name: doc
  - name: deploy
    if: branch = master AND type != pull_request

env:
  global:
  - JAVA_OPTS="-Xms512m -Xmx1024m"

jobs:
  include:
  - stage: build
    script: ./gradlew clean build :arrow-benchmarks-fx:jmhClasses
  - stage: doc
    before_install:
      - gem update --system
      - gem install bundler
    install:
      - bundle install --gemfile modules/docs/arrow-docs/Gemfile --path vendor/bundle
    script: |
      ./gradlew dokka
      ./gradlew :arrow-docs:runAnk
      travis_wait env BUNDLE_GEMFILE=modules/docs/arrow-docs/Gemfile bundle exec jekyll build -s modules/docs/arrow-docs/build/site -d modules/docs/arrow-docs/build/_site
  - stage: deploy
    script:
    - ./deploy-scripts/deploy.sh
