version: 2

jobs:
  build:
    working_directory: ~/arrow
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      GRADLE_OPTS: -Xmx1024m -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run:
          name: Clean build
          command: ./gradlew --no-daemon --max-workers 2 clean build
