name: "<arrow-library>: build documentation"

on: pull_request

jobs:
  <arrow-library>_build_documentation:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m
      ARROW_LIB: <arrow-library>

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout orchestrator
      run: |
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow.git --depth 1 --no-single-branch
    - name: Prepare env
      run: brew install hub
    - name: Install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | cut -d/ -f3)
        $BASEDIR/arrow/scripts/action-install.sh $ARROW_LIB $BRANCH_NAME
    - name: Generate API doc and validate
      run: ./gradlew buildArrowDoc
