name: "Build libraries"

on:
  pull_request:
    paths:
    - 'arrow-libs/**'
    - '.github/**'

jobs:
  build:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      working-directory: arrow-libs
      run: ./gradlew build
