name: "Build libraries"

on: pull_request

jobs:
  build:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - name: Set env
      run: |
        echo "$JAVA_HOME_8_X64/bin" >> $GITHUB_PATH
        echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      working-directory: arrow-libs
      run: ./gradlew build
