name: "Check Doc Integration"

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'templates/**'
    - '**.md'

jobs:
  check-doc-integration:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms3g

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: ./scripts/check-doc-integration.sh
