name: "Check Doc Integration"

on:
  pull_request:
    paths-ignore:
    - 'docs/**'

jobs:
  check-doc-integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: ./scripts/check-doc-integration.sh
