name: "Publish Arrow Stack (BOM file)"

on:
  push:
    branches:
    - master
    paths:
    - 'gradle.properties'
    - 'gradle/**'
    - 'scripts/**'
    - 'BOM-file/**'

jobs:
  publish-arrow-stack:

    env:
      BASEDIR: ${{github.workspace}}/..
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Check versions"
      id: versions
      run: |
        LATEST_PUBLISHED_RELEASE_VERSION=$(curl -X GET https://api.bintray.com/packages/arrow-kt/arrow-kt/arrow/versions/_latest | jq -r '.name')
        RELEASE_VERSION=$(grep LATEST_VERSION gradle.properties | cut -d= -f2)
        NEW_RELEASE_VERSION_EXISTS=$([ "$LATEST_PUBLISHED_RELEASE_VERSION" == "$RELEASE_VERSION" ] && echo '0' || echo '1')
        echo "::set-output name=release-version::$RELEASE_VERSION"
        echo "::set-output name=new-release-version-exists::$NEW_RELEASE_VERSION_EXISTS"
    - name: "Publish into OSS"
      run: ./gradlew publish
      working-directory: BOM-file
    - name: "Publish into Bintray"
      if: steps.versions.outputs.new-release-version-exists == '1'
      run: |
        echo "Update version ..."
        perl -pe "s/^VERSION_NAME=.*/VERSION_NAME=${{ steps.versions.outputs.release-version }}/g" -i gradle.properties
        . scripts/commons4gradle.sh
        useLocalSetup
        cd BOM-file
        ./gradlew publish
