name: "Publish Arrow Stack (BOM file)"

on:
  push:
    branches:
    - main
    paths:
    - 'arrow-libs/**'
    - 'arrow-stack/**'
    - '.github/**'

jobs:
  publish-arrow-stack:

    env:
      BASEDIR: ${{github.workspace}}/arrow-libs
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

    runs-on: macos-latest
    defaults:
      run:
        working-directory: arrow-stack

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Setup"
      run: brew install grep
    - name: "Set env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/set-env.sh
    - name: "Show env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/show-env.sh
    - name: "Update version when release"
      if: env.NEW_RELEASE_VERSION_EXISTS == '1'
      run: perl -pe "s/^VERSION_NAME=.*/VERSION_NAME=$RELEASE_VERSION/g" -i $BASEDIR/gradle.properties
    - name: "Publish"
      run: |
        ./gradlew publish
        echo "$(cat $BASEDIR/gradle.properties | grep VERSION_NAME | cut -d'=' -f2) deployed!"
