name: "Run Gradle tasks"

on: pull_request

jobs:
  run-tasks:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-16.04, macos-latest]
        fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Install all with local dependencies
      run: |
        # sed into 2 steps because of macOS compatibility
        sed -e "s/git@github.com:/https:\/\/github.com\//g" scripts/commons4gradle.sh > scripts/commons4gradle.sh.tmp
        mv scripts/commons4gradle.sh.tmp scripts/commons4gradle.sh; chmod +x scripts/commons4gradle.sh
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow-core.git
        cd arrow-core
        sed -e "s/git pull//g" scripts/checkout-orchestrator.sh > scripts/checkout-orchestrator.sh.tmp
        mv scripts/checkout-orchestrator.sh.tmp scripts/checkout-orchestrator.sh; chmod +x scripts/checkout-orchestrator.sh
        ./gradlew installAllWithLocalDeps
    - name: Build with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildWithLocalDeps
    # TODO. Flaky tests with Fx
    #- name: Build all with local dependencies
    #  run: |
    #    cd $BASEDIR/arrow-core
    #    ./gradlew buildAllWithLocalDeps
