name: "Run Gradle tasks"

on: pull_request

jobs:
  run-tasks:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Prepare env
      run: |
        perl -pe "s/git\@github.com:/https:\/\/github.com\//g" -i scripts/commons4gradle.sh
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow-core.git
        cd arrow-core
        perl -pe "s/git pull//g" -i scripts/checkout-orchestrator.sh
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        replaceGlobalPropertiesbyLocalConf gradle.properties
    - name: Build with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildWithLocalDeps
    - name: Clean and prepare env
      run: |
        cd $BASEDIR/arrow-core
        git checkout .
        perl -pe "s/git pull//g" -i scripts/checkout-orchestrator.sh
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        replaceGlobalPropertiesbyLocalConf gradle.properties
    - name: Build Doc with local dependencies
      run: |
        cd $BASEDIR/arrow-core
        ./gradlew buildArrowDocWithLocalDeps
